name: env_1
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy
  - scipy
  - pandas
  - pyyaml
  - gymnasium
  - matplotlib
  - scikit-learn
  - pytorch
  - tensorboard
  - ipykernel
  - pip:
      - -e ./pneu_utils
      - -e ./pneu_ref
      - -e ./pneu_env
      - -e ./pneu_rl
